### ISSUE TITLE
Benchmark has failed on allocating_hosts with reason: hosts_are_busy

### ISSUE THREAD

**Issue by KrlosWd** [machinezone/mzbench#110]
Hello, 

Is there a more detailed documentation on how to deploy worker nodes using the mzb_staticcloud_plugin? So far I have mzbench installed in one localmachine 192.168.144.2, and want to have 3 more additional machines as worker nodes (192.168.144.3, 192.168.144.4, 192.168.144.5). 

I added the following entry in my configuration file as indicated by the documentation: https://machinezone.github.io/mzbench/cloud_plugins/#static-cloud

```
{cloud_plugins, [{static, #{module => mzb_staticcloud_plugin,
                           hosts => ["192.168.144.3", "192.168.144.4", "192.168.144.5"]
                           }}]},
```

However when I start a benchmark, I'm getting the following error:

```
23:32:46.736 [error] [ API ] <0.349.0> Stage 'pipeline - allocating_hosts': failed
Benchmark has failed on allocating_hosts with reason:
hosts_are_busy

Stacktrace:  ...
```

I'm monitoring the connection between the controller host (192.168144.2) and  the intended worker nodes (192.168.144.3, 192.168.144.4, 192.168.144.5) and nothing seems to be going on.  I am missing something obvious? any help would be appreciated!,

Best,
Carlos

**Comment by timofey-barmin** [comment]
Hi KrlosWd,
I see two possible reasons:
1) we allocate 1 extra node for orchestrating and metric aggregation purposes. So if you are trying to start 3 nodes benchmark it will probably fail because it will try to allocate 4 nodes. That's sound a little weird but that's how it is. Please try starting 2 nodes bench.
2) there is another benchmark that uses this hosts. Try searching by word 'running' or simply restart the server to make sure that everything stopped (bin/mzbench restart_server)

**Comment by KrlosWd** [comment]
Hi timofey-barmin

Thanks for your answer, I managed to make it work by setting nodes to 2 as you suggested. 

Thanks a lot again,
Best,
Carlos
