### ISSUE TITLE
0.5.0 - Troubleshooting Connect Cluster Error

### ISSUE THREAD

**Issue by pulltab** [machinezone/mzbench#97]
Back again.

Made it a little further, however, I have noticed a change in behavior that I am having some trouble chasing down from the log output.

I am seeing the following on my failed run:

```
01:11:06.617 [error] [ API ] <0.945.0> Stage 'pipeline - connect_nodes': failed
Benchmark has failed on connect_nodes with reason:
{connect_cluster_error,timeout}

Stacktrace: [{mzb_api_bench,handle_stage,3,
                            [{file,"/opt/mzb/server/_build/default/deps/mzbench_api/src/mzb_api_bench.erl"},
                             {line,223}]},
             {mzb_pipeline,'-handle_cast/2-fun-0-',6,
                           [{file,"/opt/mzb/server/_build/default/deps/mzbench_api/src/mzb_pipeline.erl"},
                            {line,172}]}]
```

Are there some new/different port assumptions between 0.5.0 and the previous version?

**Comment by timofey-barmin** [comment]
Good to hear from you again, John!

AFAIR ports 4801,4802,4803 should be accessible on server from workers 
and 4804 is used between workers

The error looks like the workers can't connect to each other using port 4804

**Comment by pulltab** [comment]
4804 I managed to reverse engineer.  50%, not so bad.

After adding ingress 4803 things are working again.  Thanks!

**Comment by qrilka** [comment]
@timofey-barmin I think it's worth to be mentioned in the docs - e.g. I also was hit by this :)

**Comment by parsifal-47** [comment]
@qrilka 
AFAIK docs are updated, you could find this information here:
https://github.com/machinezone/mzbench/blob/master/doc/cloud_plugins.md#amazon-ec2

**Comment by qrilka** [comment]
oh thanks @parsifal-47 
I must have missed those lines somehow, otherwise I have found that even if it's said that
```
Minimally, the config requires instance_spec and config keys specified. 
```
plugin code needs `instance_user` to be present and also it's not clear why you show `{group_set, ""}` in the docs when that set is a list of strings (I know that `"" == []` but it's not intuitive). Also it appears that `iam_instance_profile_name` is required but probably that's more about `erlcloud` though it would help if examples were more or less close to be usable in production
